Fourth homework
daria-proleskovska/projector pull request #4
Opened 2023-11-07 14:10 UTC by daria-proleskovska

Initial commit

2023-11-09 08:40 UTC, myroslav-kolomiiets requested changes
Все дуже добре, є одне питання

2023-11-09 08:40 UTC, myroslav-kolomiiets commented on hw4/index.js
> +myPets
А яка мета такого виклику функцій? Чому вони повертають посилання на об'єкт?

2023-11-20 23:08 UTC, daria-proleskovska commented on hw4/index.js
> +myPets
Щоб можна було викликати функціїї одну за одною. Хіба так не можна?

2023-11-28 10:36 UTC, myroslav-kolomiiets requested changes

2023-11-28 10:36 UTC, myroslav-kolomiiets commented on hw4/index.js
> +myPets
Я розумію що робить цей код)

Я не розумію навіщо це тут потрібно. І взагалі де це може бути потрібно.

Це неочевидний код, який не несе, на мою думку, ніякої практичної користі. Я не рекомендую використовувати такий підхід.

Якщо маєш іншу думку, аргументуй.

2023-12-04 09:44 UTC, myroslav-kolomiiets approved these changes

2023-12-11 17:24 UTC, merged