Fifth homework
daria-proleskovska/projector pull request #5
Opened 2023-11-08 22:37 UTC by daria-proleskovska

Initial commit

2023-11-09 09:04 UTC, myroslav-kolomiiets requested changes

2023-11-09 09:04 UTC, myroslav-kolomiiets commented on hw5/task1/script.js
> +let headerTwo = document.querySelector('#headerTwo');
Я згоден, і сам рекомендую використовувати querySelector для всього, але по умові задачі, в навчальних цілях 

> Кожен селектор має бути унікальним (тобто всі мають бути створені за допомогою різних методів)

2023-11-09 09:04 UTC, myroslav-kolomiiets commented on hw5/task1/script.js
> +let headerTwo = document.querySelector('#headerTwo');
Також, оскільки ці змінні не перезаписуються, то краще об'являти їх як константи

2023-11-09 09:04 UTC, myroslav-kolomiiets commented on hw5/task2/script.js
> +    }
```suggestion
    const buttonState = localStorage.getItem('mainButtonState');

    if (buttonState === 'on') {
        applyOnState();
    } else if (buttonState === 'off') {
        applyOffState();
    }
```

2023-11-09 09:04 UTC, myroslav-kolomiiets commented on hw5/task2/script.js
> +            localStorage.setItem('stateChangeDate', formatDate(new Date()));
```suggestion
            localStorage.setItem('mainButtonState', 'on');
            localStorage.setItem('stateChangeDate', formatDate(new Date()));
```
Цю логіку також можна винести в applyOnState(); і в applyOffState(); відповідно

2023-11-09 09:04 UTC, myroslav-kolomiiets commented on hw5/task2/script.js
> +        message.innerHTML = `<p>Last turn on: ${localStorage.getItem('stateChangeDate')}</p>`;
Єфективніше створити параграф в верстці і міняти тільки innerText, а не міняти кожного разу весь innerHTML

2023-11-28 10:51 UTC, myroslav-kolomiiets requested changes

2023-11-28 10:51 UTC, myroslav-kolomiiets commented on hw5/task2/script.js
> +            });
Метод `toLocaleString` 

> returns a string with a language-sensitive representation of this date

Ти ж використовуєш його, без того, для чого він власне створений.

Для отримання необхідних значень з дати, треба використовувати відповідні методи.

Тому весь цей код можна зробити наступним чином.

```suggestion
        const day = dateObj.getDay();
        const month = dateObj.getMonth();
        const year = dateObj.getFullYear();
        const hour = dateObj.getHours();
        const minute = dateObj.getMinutes();
        const second = dateObj.getSeconds();

        return `${day}-${month}-${year} ${hour}:${minute}:${second}`;
```

2023-11-29 14:53 UTC, daria-proleskovska commented on hw5/task2/script.js
> +            });
Цей код не робить абсолютно те саме, що і мій.
Має бути не <code>dateObj.getDay();</code> а <code>dateObj.getDate();</code> 
Та <code>month = dateObj.getMonth() + 1;</code> бо відлік починається з нуля.

А як зробити, щоб години, хвилини та секунди були з двох цифр?

2023-12-04 09:42 UTC, myroslav-kolomiiets requested changes

2023-12-04 09:42 UTC, myroslav-kolomiiets commented on hw5/task2/script.js
> +            });
А мені й не стоїть задача написати за тебе робоче рішення)

Мені треба вказати на очевидну проблеми, і підштовхнути в напрямку її рішення.

> А як зробити, щоб години, хвилини та секунди були з двох цифр?

А ти пробувала запустити мій код? Там власне години, хвилини та секунди з двох цифр.

2023-12-14 08:30 UTC, myroslav-kolomiiets approved these changes

2023-12-14 10:56 UTC, merged